### ISSUE TITLE
Move tests to GitHub Actions

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1279]
We've had several PR test outages due to Jenkins updates over the last few months.

Depending on the outage, the resolution to these outages took me from a few minutes up to multiple days.

It's probably a better use of my/our time to port our jobs to GitHub Actions. The following PR tests would need to be ported:

- [x] Mypy #1280
- [x] Ruff #1280
- [x] Tests on Linux (Ubuntu, Python 3.7) #1280
- [x] Tests on Mac (MacOS, Python should be 3.8, now running 3.9) #1280
- [x] Tests on Windows (Windows, Python 3.8) #1280

Additionally, we may want to port the three remaining validation checks (the cross-env check is already in GitHub Actions):

 - [x] Validate attestation (deprecrated functionality) tutorial #1283
 - [x] Validate identity tutorial #1283
 - [x] Validate documentation #1283

The post-merge tests still seem to be working reliably (Mutation tests + Linux, Mac, Windows coverage listed in the README). Perhaps we should port these at a later date. If we do end up porting these, it concerns the following jobs (we don't really care about the Python versions here):

 - [x] Tests with coverage on Linux https://github.com/Tribler/py-ipv8/pull/1290
 - [x] Tests with coverage on Mac https://github.com/Tribler/py-ipv8/pull/1290
 - [x] Tests with coverage on Windows https://github.com/Tribler/py-ipv8/pull/1290
 - [x] Mutation tests (this is a **HUGE** job and should be the very very very last thing we port) https://github.com/Tribler/py-ipv8/pull/1320

**Comment by qstokkink** [comment]
Side note: this issue only covers tests due to (proposed) merges. Our network health jobs (peer discovery health, default community peer discovery health, and bootstrap connectivity) would remain on Jenkins.

**Comment by qstokkink** [comment]
We got to the "very very very last thing" a lot sooner than I expected. However, there are [some issues](https://github.com/Tribler/py-ipv8/issues/1254#issuecomment-1896079690) with resolving this last bullet point. I'll scale down this issue to low priority.

**Comment by qstokkink** [comment]
Apparently the MutPy changes are not lost at all. https://github.com/Tribler/py-ipv8-mutation-libraries/issues/1#issue-771999920 In that case, we can clean everything up neatly.

**Comment by qstokkink** [comment]
Once https://github.com/Tribler/mutpy/issues/1 is resolved, this repo should make use of the sanitized fork. Then the approach of https://github.com/Tribler/py-ipv8/issues/1254#issuecomment-1896079690 could be followed to implement the GitHub Action.

**Comment by qstokkink** [comment]
The mutpy fork issue has now been resolved. An `.md` report can be generated with:

```bash
bin/github_report.py --codebase ipv8
```
