### ISSUE TITLE
ID 2.0

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#733]
The identity layer has remained virtually unchanged for more than 2 years in IPv8, but is in need of some maintenance. Some initial design decisions require work to improve security and functionality, though they break the disk format and protocol:

 - [x] Add REST API access key (@egbertbouman made this for Tribler already - and will provide this PR). #773
 - [x] Refactor REST API design (URL parameters are not pretty 😃 ). #742 #772
 - [x] Add DAG Trustchain derivative for selective disclosure of metadata. #754 #758
 - [x] Add pseudonym chains --completely devoid of all metadata-- for storage of attribute commitments for ZKPs. #738
 - [x] Add pseudonym REST API bindings for easy pseudonym control. #759
 - [x] Add additional advanced controls for attestation REST API. #772
 - [x] Update documentation. #779

Once this is all complete, Trustchain will probably be moved into the `Tribler` repository. The identity solution may be moved into its own new repository.

**Comment by synctext** [comment]
Forking software is something that is quite a red flag for me. 

Something that is virtually unchanged for more than 2 years is clearly stable and low maintenance, on the other hand. Can you do an ID2.0 upgrade both the Tribler usage and identity usage?
Your list seems like solid positive maintenance upgrade.

> The identity solution may be moved into its own new repository.

Lets discuss matters first, before any changes are made. I have a preference for mono-repo development. Why not simply another branch in the repo?

**Comment by qstokkink** [comment]
> Something that is virtually unchanged for more than 2 years is clearly stable and low maintenance, on the other hand. Can you do an ID2.0 upgrade both the Tribler usage and identity usage?

I agree and I would not have posted this issue if it was not a pressing concern. Stable as it may be, our identity layer has security concerns regarding disclosure of metadata. This can still be somewhat controlled by patching the current Trustchain functionality for production use. However, with Trustchain also being **forked already** for currency use, with **more aggressive spreading** of blocks in the fundamental protocol (where blocks contain metadata in the case of identity), now is the time to fix all of this. We have reached the breaking point for both use cases on the same chain type.

> Why not simply another branch in the repo?

I'd like to avoid shipping dead code in a repository. IPv8 is being shipped for both the Tribler and identity use cases. Tribler does not use the identity part of IPv8 at all, inflating its binary size and having its interpreter load code that will never be used. That said, this is not a pressing issue, just some code organization: the identity refactoring has the utmost priority now.

**Comment by synctext** [comment]
fixing security, more then just cosmetics! good.
dead code? We don't ship non-master branches in our installer right?

**Comment by qstokkink** [comment]
> dead code? We don't ship non-master branches in our installer right?

Sorry, I was referring to keeping the identity code on the master branch. Moving the code to a branch is a perfectly fine solution 👍

**Comment by synctext** [comment]
What are our plans? https://github.com/Tribler/py-ipv8 branches: ```master``` and ```master-identity``` or something? The master-identity branch includes the security fixes, while we keep using master branch for Tribler matters?

**Comment by qstokkink** [comment]
> What are our plans?

Short term I will not change anything.

Once the required changes are made, I think we should reflect on the state of the code again. If the identity primitives can still be used for currency, I'd like to avoid branching off or changing repository. If none or a large part of the components cannot be reused, identity should be moved to its own branch.

**Comment by qstokkink** [comment]
During performance testing I found the IRMA integration to be broken after the last refactoring. This should be fixed with the ID 2.0 refactoring. We should also create a tool to keep the keys of signing authorities up-to-date (but not ship these by default).

**Comment by qstokkink** [comment]
With the merge of #759, our identity is now decoupled from Trustchain-as-a-Currency and we can fork behaviors now. With this fork in behavior we can also have a discussion on where the Trustchain code should be located. But this discussion should probably not be in this issue 😃

**Comment by qstokkink** [comment]
I thought I could just gung-ho the REST API.. but I don't have a great design yet:

```
/identity/peers -> [Peer]
/identity/create -> PseudonymName
/identity/list -> [PseudonymName]
/identity/{PseudonymName}/list -> [Credential]
/identity/{PseudonymName}/create -> Credential
/identity/{PseudonymName}/{Credential}/attest/{PseudonymName} -> success?
/identity/{PseudonymName}/{Credential}/attest/requests -> [AttestationRequest]
/identity/{PseudonymName}/{Credential}/verify/{matching_value} -> match fraction
/identity/{PseudonymName}/{Credential}/verify/requests -> [VerificationRequest]
/identity/{PseudonymName}/{Credential}/allow_attest/{Peer}
/identity/{PseudonymName}/{Credential}/allow_verify/{Peer}
```

I'm not sure how to elegantly include the `allow_attest` and `allow_verify` in there.

**Comment by qstokkink** [comment]
Perhaps this is better:

```
/identity/peers -> [Peer]
/identity/create -> PseudonymName
/identity/list -> [PseudonymName]
/identity/{PseudonymName}/list -> [Credential]
/identity/{PseudonymName}/create -> Credential
/identity/{PseudonymName}/{Credential}/attest/allow/{Peer}
/identity/{PseudonymName}/{Credential}/attest/create/{PseudonymName} -> success?
/identity/{PseudonymName}/{Credential}/attest/requests -> [AttestationRequest]
/identity/{PseudonymName}/{Credential}/verify/allow/{Peer}
/identity/{PseudonymName}/{Credential}/verify/create/{matching_value} -> match fraction
/identity/{PseudonymName}/{Credential}/verify/requests -> [VerificationRequest]
```
